### ISSUE TITLE
cannot build with latest js_of_ocaml (3.0.2). Works find with 2.8.4

### ISSUE THREAD

**Issue by jstafford** [facebook/flow#5877]
To build flow for locally testing a proposed change, the readme suggests has the following step:
```
opam install -y js_of_ocaml
```
However (on macs at least) this installs version 3.0.2
Then when running the command: 
```
make js
```
It fails with the error:
```
File "src/flow_dot_js.ml", line 315, characters 40-60:
Error: Unbound value Sys_js.register_file
```
This problem does not occur in 2.8.4. 
If you have followed the readme, to fix this issue, you can execute the following commands:
```
opam pin add js_of_ocaml 2.8.4
make clean
make
make js
```
I didn't see a way to clean just the make js output, and if you try to rebuild without a clean after downgrading js_of_ocaml it will fail.

The short term fix I would like is to change the directions in the readme to 
```
opam install -y js_of_ocaml.2.8.4
```

The long term fix should be to get this working with the latest js_of_ocaml

**Comment by jstafford** [comment]
Oops. I wasn't on the branch I thought I was. This may not be a real issue. Trying again.

**Comment by jstafford** [comment]
Yep. I was actually looking at a fork of flow that was out of date. My bad.
